//! The nginx front-door config renderer.
//!
//! **Pure function: registry in, config text out.** No filesystem, no Docker, no
//! nginx, no root, no clock. That is the whole point of this module — it is the
//! one component whose output can take down every service on the host at once,
//! so it has to be testable in milliseconds and exhaustively.
//!
//! ## Determinism
//!
//! The same registry always produces byte-identical output:
//!
//! * apps are sorted by name, so filesystem order cannot leak in;
//! * nothing timestamps the output, because a timestamp would make every
//!   `swapdock render` differ from the live file and turn the diff into noise;
//! * indentation, spacing and line endings are fixed.
//!
//! That is what makes `diff <(swapdock render) /etc/nginx/conf.d/front-door.conf`
//! a meaningful question rather than a coin flip.
//!
//! ## What is not rendered here
//!
//! `http {}`-level settings — `log_format`, the `Upgrade` map, `client_max_body_size`
//! — belong to a hand-written file, because they are not derived from the registry.
//! So does `snippets/proxy-common.conf`, which each container block includes.

use crate::registry::{App, Kind, normalize_hostname};

/// Access log every generated block writes to. Shared so one rotation covers all.
pub const ACCESS_LOG: &str = "/var/log/nginx/front-door.access.log";

/// Format name declared in the hand-written `http {}` block.
pub const LOG_FORMAT: &str = "swapdock";

/// Hand-written include shared by container blocks.
pub const PROXY_COMMON: &str = "/etc/nginx/snippets/proxy-common.conf";

/// Indentation inside a server block.
const INDENT: &str = "    ";

/// Renders the whole front-door file.
///
/// Total by design: it never fails, so it can diff a broken registry and show the
/// operator what is wrong. Problems are emitted as `# PROBLEM:` comments inside
/// each block, and `crate::validator` refuses to apply a config that has any.
pub fn render(apps: &[App]) -> String {
    let mut sorted: Vec<&App> = apps.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::with_capacity(256 * apps.len() + 512);

    out.push_str("# front-door.conf\n");
    out.push_str("#\n");
    out.push_str("# GENERATED BY swapdock. DO NOT EDIT BY HAND.\n");
    out.push_str("#\n");
    out.push_str("# Derived state: every line here comes from the registry in\n");
    out.push_str("# /srv/swapdock/apps. Change a registry file and re-render.\n");
    out.push_str("#\n");
    out.push_str("# Regenerating is safe. This file holds no hand edits.\n");
    out.push_str("#\n");
    out.push_str("# Include this file from inside `http {}`; the log_format, the\n");
    out.push_str("# Upgrade map and client_max_body_size live in conf.d/00-swapdock-http.conf.\n");

    if sorted.is_empty() {
        out.push_str("#\n# No apps in the registry.\n");
        return out;
    }

    let names: Vec<&str> = sorted.iter().map(|a| a.name.as_str()).collect();
    out.push_str("#\n# apps: ");
    out.push_str(&names.join(", "));
    out.push('\n');

    for app in sorted {
        out.push('\n');
        render_app(&mut out, app);
    }

    out
}

/// True when this app is behind the front door and needs a server block.
///
/// A container app only does once it publishes a *back* port. Until then the
/// container still holds the front port itself, so nginx cannot bind it, and
/// emitting a block would produce a config that fails to load. Static apps have
/// no port at all and are always fronted.
fn is_fronted(app: &App) -> bool {
    match app.kind {
        Kind::Static => true,
        Kind::Container => app.live_port.is_some(),
    }
}

/// Appends one app's server block, preceded by a comment header.
fn render_app(out: &mut String, app: &App) {
    out.push_str("# ---- ");
    out.push_str(&app.name);
    out.push_str(" ----\n");

    for problem in app.problems() {
        out.push_str("# PROBLEM ");
        out.push_str(match problem.severity {
            crate::registry::Severity::Error => "error",
            crate::registry::Severity::Warning => "warning",
        });
        out.push_str(": [");
        out.push_str(problem.code);
        out.push_str("] ");
        out.push_str(&problem.message.replace('\n', " "));
        out.push('\n');
    }

    // Summary line, so the file explains itself without the registry.
    match app.kind {
        Kind::Container => {
            out.push_str("# container, strategy ");
            out.push_str(app.strategy.as_str());
            match &app.release {
                Some(r) => {
                    out.push_str(", release ");
                    out.push_str(r);
                }
                None => out.push_str(", no release yet"),
            }
            if app.writes_state {
                out.push_str(" (writes local state, so a swap would give two writers)");
            }
            out.push('\n');
        }
        Kind::Static => {
            out.push_str("# static, root ");
            out.push_str(app.root.as_deref().unwrap_or("<unset>"));
            out.push('\n');
        }
    }

    if !is_fronted(app) {
        out.push_str("# not yet fronted: this container still publishes its front port,\n");
        out.push_str("# so nginx cannot bind it yet. Run `swapdock` for this app first.\n");
        return;
    }

    out.push_str("server {\n");

    for addr in app.listen_addrs() {
        out.push_str(INDENT);
        out.push_str("listen ");
        out.push_str(&addr);
        out.push(':');
        out.push_str(&app.front_port.to_string());
        out.push_str(";\n");
    }

    out.push_str(INDENT);
    out.push_str("server_name ");
    if app.hostnames.is_empty() {
        // Nothing routes here yet, but the block still has to be valid.
        out.push_str("_;\n");
    } else {
        out.push_str(&app.hostnames.join(" "));
        out.push_str(";\n");
    }

    out.push('\n');
    out.push_str(INDENT);
    out.push_str("access_log ");
    out.push_str(ACCESS_LOG);
    out.push(' ');
    out.push_str(LOG_FORMAT);
    out.push_str(";\n");

    match app.kind {
        Kind::Container => {
            // `proxy_pass` is only legal inside `location` (or `if in location`,
            // which nobody should write). Emitting it at server level produces a
            // file that fails `nginx -t`, which is how this was found.
            out.push('\n');
            out.push_str(INDENT);
            out.push_str("location / {\n");
            out.push_str(INDENT);
            out.push_str(INDENT);
            out.push_str("include ");
            out.push_str(PROXY_COMMON);
            out.push_str(";\n");

            // `other` is impossible here: the port is validated against the slot
            // pair before apply. Fall back to the live port so the file is still
            // readable if it is ever rendered from a broken registry.
            let target = app.live_port.unwrap_or(app.front_port);
            out.push_str(INDENT);
            out.push_str(INDENT);
            out.push_str("proxy_pass http://127.0.0.1:");
            out.push_str(&target.to_string());
            out.push_str(";\n");
            out.push_str(INDENT);
            out.push_str("}\n");
        }
        Kind::Static => {
            out.push('\n');
            out.push_str(INDENT);
            out.push_str("root ");
            out.push_str(app.root.as_deref().unwrap_or("/srv/www/unset"));
            out.push_str(";\n");
            out.push_str(INDENT);
            out.push_str("index index.html;\n");
            // `=404` and not a bare `/index.html`: a missing asset must return 404,
            // not index.html with a 200. A single-page app that needs history
            // fallback adds `include snippets/spa-fallback.conf;` after this line.
            out.push_str(INDENT);
            out.push_str("try_files $uri $uri/ =404;\n");
        }
    }

    out.push_str("}\n");
}

/// Every hostname the rendered config claims, normalised, sorted and deduplicated.
///
/// Used by the validator to compare the registry against the tunnel ingress.
pub fn rendered_hostnames(apps: &[App]) -> Vec<String> {
    let mut hosts: Vec<String> = apps
        .iter()
        .flat_map(|a| a.hostnames.iter())
        .map(|h| normalize_hostname(h))
        .collect();
    hosts.sort();
    hosts.dedup();
    hosts
}

/// Every `listen` address and port the rendered config binds, sorted.
///
/// A cross-app duplicate here is what would make nginx refuse to start, or worse,
/// silently bind only one of them.
pub fn rendered_listeners(apps: &[App]) -> Vec<(String, u16)> {
    let mut out: Vec<(String, u16)> = apps
        .iter()
        .flat_map(|a| {
            a.listen_addrs()
                .into_iter()
                .map(move |addr| (addr, a.front_port))
        })
        .collect();
    out.sort();
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::tests::{sample, sample_static};
    use crate::registry::{ImageRegistry, Strategy};

    fn container() -> App {
        sample()
    }

    fn static_app() -> App {
        App {
            image_repo: None,
            release: None,
            old_release: None,
            health_url: None,
            ..sample_static()
        }
    }

    // ---- shape ----

    #[test]
    fn an_empty_registry_renders_a_valid_empty_file() {
        let out = render(&[]);
        assert!(out.contains("GENERATED BY swapdock"));
        assert!(out.contains("No apps in the registry"));
        assert!(!out.contains("server {"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn proxy_pass_is_inside_a_location_block() {
        // Regression: proxy_pass at server level fails `nginx -t` with
        // `"proxy_pass" directive is not allowed here`. The location wrapper is
        // what makes the rendered file loadable.
        let out = render(&[container()]);
        assert!(out.contains("    location / {\n"), "{out}");

        let mut in_location = false;
        let mut server_depth_proxy = false;
        for line in out.lines() {
            if line == "    location / {" {
                in_location = true;
            } else if line == "    }" {
                in_location = false;
            } else if line.starts_with("        proxy_pass ") {
                assert!(in_location, "proxy_pass outside location: {line}");
            } else if line.starts_with("    proxy_pass ") {
                server_depth_proxy = true;
            }
        }
        assert!(!server_depth_proxy, "no server-level proxy_pass allowed");
    }

    #[test]
    fn a_container_block_has_the_expected_directives() {
        let out = render(&[container()]);
        assert!(out.contains("listen 127.0.0.1:8001;"), "{out}");
        assert!(out.contains("server_name example.com;"), "{out}");
        assert!(out.contains(&format!("include {PROXY_COMMON};")), "{out}");
        assert!(out.contains("proxy_pass http://127.0.0.1:9000;"), "{out}");
        assert!(
            out.contains(&format!("access_log {ACCESS_LOG} {LOG_FORMAT};")),
            "{out}"
        );
        assert!(out.starts_with("# front-door.conf"), "{out}");
    }

    #[test]
    fn a_static_block_uses_root_not_proxy_pass() {
        let out = render(&[static_app()]);
        assert!(out.contains("root /srv/www/docs/current;"), "{out}");
        assert!(out.contains("try_files $uri $uri/ =404;"), "{out}");
        assert!(!out.contains("proxy_pass"), "static must not proxy: {out}");
        assert!(
            !out.contains(PROXY_COMMON),
            "static needs no proxy include: {out}"
        );
    }

    #[test]
    fn a_static_block_serves_a_missing_asset_as_404_not_as_index() {
        // The classic confusing bug: index.html returned with 200 for a missing
        // JavaScript file. The `=404` is what prevents it.
        let out = render(&[static_app()]);
        assert!(out.contains("=404"), "{out}");
        assert!(
            !out.contains("/index.html;"),
            "no bare index fallback: {out}"
        );
    }

    #[test]
    fn several_hostnames_share_one_block() {
        let out = render(&[static_app()]);
        assert!(
            out.contains("server_name docs.example.com www.shop.example.com;"),
            "{out}"
        );
        assert_eq!(out.matches("server {").count(), 1, "one block, both names");
    }

    #[test]
    fn an_app_with_no_hostname_still_renders_valid_config() {
        let mut app = container();
        app.hostnames = vec![];
        let out = render(&[app]);
        assert!(out.contains("server_name _;"), "{out}");
    }

    #[test]
    fn a_second_listen_address_becomes_a_second_listen_line() {
        let mut app = container();
        app.listen = vec!["127.0.0.1".into(), "192.0.2.10".into()];
        let out = render(&[app]);
        assert!(out.contains("listen 127.0.0.1:8001;"), "{out}");
        assert!(out.contains("listen 192.0.2.10:8001;"), "{out}");
    }

    // ---- determinism ----

    #[test]
    fn output_does_not_depend_on_input_order() {
        let a = container();
        let mut b = static_app();
        b.name = "aaa".into();
        let mut c = static_app();
        c.name = "zzz".into();
        c.front_port = 8013;
        c.slot = 4;

        let forward = render(&[a.clone(), b.clone(), c.clone()]);
        let reversed = render(&[c, b, a]);
        assert_eq!(forward, reversed, "input order must not change the output");
    }

    #[test]
    fn rendering_twice_is_byte_identical() {
        let apps = vec![container(), static_app()];
        assert_eq!(render(&apps), render(&apps));
    }

    #[test]
    fn the_output_carries_no_timestamp() {
        // A timestamp would make every render differ from the live file.
        let out = render(&[container()]);
        assert!(!out.contains("20"), "no year-like token: {out}");
        assert!(!out.to_lowercase().contains("generated at"), "{out}");
        assert!(!out.contains("Z\n"), "{out}");
    }

    #[test]
    fn the_file_ends_with_exactly_one_newline() {
        let out = render(&[container(), static_app()]);
        assert!(out.ends_with("}\n"));
        assert!(!out.ends_with("\n\n"), "no blank line at the end");
    }

    #[test]
    fn no_line_has_trailing_whitespace() {
        let out = render(&[container(), static_app()]);
        for (n, line) in out.lines().enumerate() {
            assert_eq!(
                line.trim_end(),
                line,
                "line {} has trailing whitespace: {line:?}",
                n + 1
            );
        }
    }

    #[test]
    fn the_output_is_ascii_with_lf_endings_only() {
        let out = render(&[container(), static_app()]);
        assert!(out.is_ascii(), "keep the config ascii");
        assert!(!out.contains('\r'), "no carriage returns");
    }

    // ---- the not-yet-fronted case ----

    #[test]
    fn a_container_without_a_live_port_gets_no_server_block() {
        // Emitting a block here would be a config nginx cannot load: the
        // container still holds that port.
        let mut app = container();
        app.live_port = None;
        app.old_port = None;
        let out = render(&[app]);

        assert!(!out.contains("server {"), "must not emit a block:\n{out}");
        assert!(out.contains("# not yet fronted"), "{out}");
        assert!(out.contains("swapdock"), "{out}");
    }

    #[test]
    fn a_static_app_is_fronted_without_any_port() {
        let out = render(&[static_app()]);
        assert!(
            out.contains("server {"),
            "static needs no port to be fronted"
        );
        assert!(!out.contains("not yet fronted"), "{out}");
    }

    #[test]
    fn the_fronted_flag_is_decided_per_kind() {
        let mut container_app = container();
        container_app.live_port = None;
        assert!(!is_fronted(&container_app));
        container_app.live_port = Some(9000);
        assert!(is_fronted(&container_app));

        let mut s = static_app();
        assert!(is_fronted(&s));
        s.live_port = None;
        assert!(is_fronted(&s), "static is fronted regardless of ports");
    }

    #[test]
    fn an_estate_of_unmigrated_apps_renders_no_listeners() {
        // What the real swapdock host looks like today: every container still
        // publishes its own front port.
        let mut a = container();
        a.live_port = None;
        a.old_port = None;
        let mut b = static_app();
        b.kind = Kind::Container;
        b.root = None;
        b.image_repo = Some("apps-b".into());
        b.health_url = Some("http://127.0.0.1/".into());
        b.live_port = None;

        let out = render(&[a, b]);
        assert!(!out.contains("server {"), "{out}");
        assert_eq!(out.matches("# not yet fronted").count(), 2, "{out}");
    }

    // ---- self-diagnosis ----

    #[test]
    fn problems_are_rendered_as_comments_next_to_the_block() {
        let mut app = container();
        app.front_port = 9001; // inside the reserved range
        let out = render(&[app]);
        assert!(
            out.contains("# PROBLEM error: [front-port-reserved]"),
            "{out}"
        );
        assert!(
            !out.lines()
                .any(|l| !l.starts_with('#') && l.contains("front-port-reserved")),
            "a problem must never appear as a live directive"
        );
    }

    #[test]
    fn the_two_writers_rule_is_visible_in_the_rendered_file() {
        let mut app = container();
        app.writes_state = true;
        app.strategy = Strategy::Swap;
        let out = render(&[app]);
        assert!(
            out.contains("PROBLEM error: [swap-with-shared-state]"),
            "{out}"
        );
        assert!(out.contains("two writers"), "{out}");
    }

    #[test]
    fn a_warning_is_labelled_as_a_warning() {
        let mut app = container();
        app.hostnames = vec![];
        let out = render(&[app]);
        assert!(
            out.contains("# PROBLEM warning: [hostnames-empty]"),
            "{out}"
        );
    }

    #[test]
    fn render_is_total_and_never_panics_on_a_broken_registry() {
        let mut app = container();
        app.name = String::new();
        app.slot = 200;
        app.front_port = 0;
        app.root = Some("/a b;c".into());
        app.kind = Kind::Static;
        app.image_repo = None;
        app.health_url = None;
        let out = render(&[app]);
        assert!(out.contains("PROBLEM"), "problems must still be reported");
    }

    // ---- summaries used by the validator ----

    #[test]
    fn rendered_hostnames_are_normalised_sorted_and_deduplicated() {
        let mut a = container();
        a.hostnames = vec!["Example.com".into(), "chat.example.com".into()];
        let mut b = static_app();
        b.hostnames = vec!["chat.example.com".into(), "files.example.com".into()];

        let hosts = rendered_hostnames(&[a, b]);
        assert_eq!(
            hosts,
            vec!["chat.example.com", "example.com", "files.example.com"]
        );
    }

    #[test]
    fn rendered_listeners_are_sorted_and_complete() {
        let mut a = container();
        a.front_port = 8001;
        let mut b = static_app();
        b.front_port = 8012;
        let mut c = container();
        c.name = "tailnet".into();
        c.front_port = 8002;
        c.listen = vec!["192.0.2.10".into()];

        assert_eq!(
            rendered_listeners(&[a, b, c]),
            vec![
                ("127.0.0.1".to_string(), 8001),
                ("127.0.0.1".to_string(), 8012),
                ("192.0.2.10".to_string(), 8002),
            ]
        );
    }

    #[test]
    fn the_summary_line_names_the_release_and_strategy() {
        let mut app = container();
        app.release = Some("9c1f2ab".into());
        app.strategy = Strategy::Swap;
        let out = render(&[app]);
        assert!(
            out.contains("# container, strategy swap, release 9c1f2ab"),
            "{out}"
        );
    }

    #[test]
    fn an_app_with_no_release_says_so() {
        let mut app = container();
        app.release = None;
        assert!(render(&[app]).contains("no release yet"));
    }

    #[test]
    fn the_default_registry_name_does_not_leak_into_the_config() {
        let mut app = container();
        app.registry = Some(ImageRegistry::Ghcr);
        let out = render(&[app]);
        assert!(
            !out.contains("ghcr"),
            "the config has no image fields: {out}"
        );
    }

    // ---- golden ----

    #[test]
    fn the_whole_file_matches_the_expected_text() {
        let mut charts = container();
        charts.name = "charts".into();
        charts.front_port = 8006;
        charts.slot = 1;
        charts.live_port = Some(9002);
        charts.old_port = Some(9003);
        charts.hostnames = vec!["shop.example.com".into()];
        charts.compose_svc = "charts".into();
        charts.env_name = "CHARTS_PORT".into();
        charts.health_url = Some("http://127.0.0.1:8001/".into());
        charts.image_repo = Some("apps-charts".into());
        charts.release = Some("a1b2c3d".into());

        let expected = "\
# front-door.conf
#
# GENERATED BY swapdock. DO NOT EDIT BY HAND.
#
# Derived state: every line here comes from the registry in
# /srv/swapdock/apps. Change a registry file and re-render.
#
# Regenerating is safe. This file holds no hand edits.
#
# Include this file from inside `http {}`; the log_format, the
# Upgrade map and client_max_body_size live in conf.d/00-swapdock-http.conf.
#
# apps: charts, portfolio

# ---- charts ----
# container, strategy swap, release a1b2c3d
server {
    listen 127.0.0.1:8006;
    server_name shop.example.com;

    access_log /var/log/nginx/front-door.access.log swapdock;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://127.0.0.1:9002;
    }
}

# ---- portfolio ----
# container, strategy swap, release 9c1f2ab
server {
    listen 127.0.0.1:8001;
    server_name example.com;

    access_log /var/log/nginx/front-door.access.log swapdock;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_pass http://127.0.0.1:9000;
    }
}
";
        assert_eq!(render(&[container(), charts]), expected);
    }
}
